plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ha7n.focusguard'
    compileSdk 36

    defaultConfig {
        applicationId 'com.ha7n.focusguard'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
