import { db } from "@/lib/db";
import { formatSAR } from "@/lib/money";
import { requireUserId } from "@/lib/current-user";
import { contributeToGoal, createGoal } from "../financial-actions";

export default async function GoalsPage() {
  const userId = await requireUserId();
  const goals = await db.goal.findMany({ where: { userId }, orderBy: [{ status: "asc" }, { targetDate: "asc" }] });
  return <div><h1 className="text-3xl font-bold mb-2">الأهداف المالية</h1><p className="muted mb-8">حوّل أهدافك إلى خطة شهرية قابلة للقياس.</p><div className="grid lg:grid-cols-[1fr_360px] gap-5"><section className="grid sm:grid-cols-2 gap-4">{goals.map(goal => { const percent = Math.min(100, goal.currentAmount.div(goal.targetAmount).mul(100).toNumber()); const months = goal.targetDate ? Math.max(1, Math.ceil((goal.targetDate.getTime() - Date.now()) / 2629800000)) : null; const monthly = months ? goal.targetAmount.minus(goal.currentAmount).div(months) : null; return <article className="card p-6" key={goal.id}><div className="flex justify-between gap-3"><h2 className="font-bold text-xl">{goal.name}</h2><span className="muted text-sm">{goal.status === "COMPLETED" ? "مكتمل" : `${percent.toFixed(0)}%`}</span></div><strong className="text-2xl block mt-4">{formatSAR(goal.currentAmount)}</strong><p className="muted">من {formatSAR(goal.targetAmount)}</p><div className="h-2 bg-black/10 rounded-full mt-4 overflow-hidden"><div className="h-full bg-teal-600 rounded-full" style={{ width: `${percent}%` }}/></div>{monthly && goal.status === "ACTIVE" && <p className="text-sm mt-4">المطلوب شهريًا: <strong>{formatSAR(monthly)}</strong></p>}{goal.status === "ACTIVE" && <form action={contributeToGoal} className="flex gap-2 mt-4"><input type="hidden" name="goalId" value={goal.id}/><input className="field" name="amount" type="number" min="0.01" step="0.01" placeholder="إضافة مبلغ" required/><button className="btn whitespace-nowrap">تحديث</button></form>}</article>; })}{!goals.length && <div className="card p-8 muted">أنشئ هدفك المالي الأول.</div>}</section><form action={createGoal} className="card p-6 space-y-4 h-fit"><h2 className="font-bold text-xl">هدف جديد</h2><input className="field" name="name" placeholder="مثال: شراء سيارة" required/><input className="field" name="targetAmount" type="number" min="1" step="0.01" placeholder="المبلغ المستهدف" required/><input className="field" name="currentAmount" type="number" min="0" step="0.01" placeholder="المبلغ الحالي"/><input className="field" name="targetDate" type="date"/><button className="btn w-full">إنشاء الهدف</button></form></div></div>;
}
