import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { formatSAR } from "@/lib/money";
import { requireUserId } from "@/lib/current-user";
import { createDebt, recordDebtPayment } from "../financial-actions";

export default async function DebtsPage() {
  const userId = await requireUserId();
  const [debts, accounts] = await Promise.all([
    db.debt.findMany({ where: { userId }, include: { payments: true }, orderBy: { createdAt: "desc" } }),
    db.account.findMany({ where: { userId, isArchived: false }, orderBy: { createdAt: "asc" } }),
  ]);
  return <div><h1 className="text-3xl font-bold mb-2">الديون والالتزامات</h1><p className="muted mb-8">سجّل الأقساط وتابع الرصيد المتبقي تلقائيًا.</p><div className="grid lg:grid-cols-[1fr_360px] gap-5"><section className="space-y-4">{debts.map(debt => { const paid = debt.payments.reduce((sum, payment) => sum.plus(payment.amount), new Prisma.Decimal(0)); const remaining = Prisma.Decimal.max(0, debt.originalAmount.minus(paid)); const percent = debt.originalAmount.gt(0) ? Math.min(100, paid.div(debt.originalAmount).mul(100).toNumber()) : 0; return <article className="card p-6" key={debt.id}><div className="flex justify-between gap-4"><div><h2 className="font-bold text-xl">{debt.name}</h2><p className="muted text-sm mt-1">{debt.status === "PAID" ? "مكتمل" : "نشط"}</p></div><span>{percent.toFixed(0)}%</span></div><div className="grid grid-cols-3 gap-3 mt-5 text-sm"><div><p className="muted">الإجمالي</p><strong>{formatSAR(debt.originalAmount)}</strong></div><div><p className="muted">المدفوع</p><strong>{formatSAR(paid)}</strong></div><div><p className="muted">المتبقي</p><strong>{formatSAR(remaining)}</strong></div></div><div className="h-2 bg-black/10 rounded-full mt-5 overflow-hidden"><div className="h-full bg-emerald-500 rounded-full" style={{ width: `${percent}%` }}/></div>{debt.status === "ACTIVE" && accounts.length > 0 && <form action={recordDebtPayment} className="grid sm:grid-cols-[1fr_1fr_auto] gap-2 mt-5"><input type="hidden" name="debtId" value={debt.id}/><input className="field" name="amount" type="number" min="0.01" max={remaining.toString()} step="0.01" placeholder="مبلغ السداد" required/><select className="field" name="accountId" required>{accounts.map(account => <option value={account.id} key={account.id}>{account.name}</option>)}</select><button className="btn">تسجيل السداد</button></form>}</article>; })}{!debts.length && <div className="card p-8 muted">لا توجد ديون مسجلة حاليًا.</div>}</section><form action={createDebt} className="card p-6 space-y-4 h-fit"><h2 className="text-xl font-bold">إضافة دين</h2><input className="field" name="name" placeholder="اسم الدين" required/><input className="field" name="originalAmount" type="number" min="1" step="0.01" placeholder="إجمالي الدين" required/><input className="field" name="installmentAmount" type="number" min="0" step="0.01" placeholder="القسط"/><input className="field" name="nextPaymentAt" type="date"/><button className="btn w-full">إضافة</button></form></div></div>;
}
